name: chromium_pickle
description: This library ports Chromium's Pickle class to Dart and provides facilities for basic binary value packing and unpacking.
version: 1.0.2

homepage: https://github.com/Kasefuchs/chromium-pickle-dart

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
